newsAPI/blog/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', NewsListView.as_view(), name='home'),
    path('cats/<slug:cat_slug>/', NewsCategory.as_view(), name='posts_by_category'),
    re_path(r'^archive/(?P<year>[0-9]{4})/', archive, name='archive'),
]

newsAPI/newsAPI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import bad_request

from blog.views import page_not_found
# from django.views.defaults import page_not_found

urlpatterns = [
    path('', include('blog.urls')),
    path('user/', include('user.urls', namespace='user')),
    # path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
]

# Тема: Обробка виключень
# Якщо DEBUG = False
# https://docs.djangoproject.com/en/5.2/ref/urls/#django.conf.urls.handler404:~:text=.MEDIA_ROOT)-,handler400,-%C2%B6
# https://docs.djangoproject.com/en/5.2/topics/http/views/#django.http.Http404:~:text=handle%20those%20errors.-,The%20Http404%20exception,-%C2%B6
# https://youtu.be/af7KvkQORwo?list=PLA0M1Bcd0w8xO_39zZll2u1lz_Q-Mwn1F&t=806
handler404 = page_not_found # сторінка не знайдена
# handler500 = server_error # помилка серверу
# handler403 = permission_denied # доступ заборонено
# handler400 = bad_request # невірний запит

newsAPI/user/urls.py
from django.urls import path
from . import views


app_name = 'user'

urlpatterns = [
#     path('login/', views.LoginView.as_view(), name='login'),
#     path('logout/', views.LogoutView.as_view(), name='logout'),
    path('', views.list_users, name='users'),
    path('<int:id>/', views.user_by_id, name='user_by_id'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('sign_up/', views.register, name='sign_up'),
]

newsAPI/blog/models.py
from django.conf import settings
from django.db import models

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(
        max_length=150,
        db_index=True) # db_index - для швидкішого пошуку
    content = models.TextField()
    image_url = models.URLField(
        max_length=500, blank=True, null=True
    )
    slug = models.SlugField(max_length=150, unique=True) # для більш зрозумілого url (тільки літери, цифри, _, -, #)
    body = models.TextField(blank=True, db_index=True) # blank=True - може бути пустим
    date_pub = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

newsAPI/user/models.py
from django.db import models

# Create your models here.

newsAPI/user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User


class LoginUserForm(forms.Form):
    username = forms.CharField(label='Логін')
    password = forms.CharField(label='Пароль')


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(label='Логін')
    password = forms.CharField(widget=forms.PasswordInput(render_value=False))
    password2 = forms.CharField(widget=forms.PasswordInput(render_value=False))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password', 'first_name', 'last_name')

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Паролі не зпівпадають.")
        return password

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такий E-mail вже існує.")
        return email

newsAPI/blog/views.py
import sys

import requests
from django.http import HttpResponseNotFound, Http404, HttpResponse, HttpResponseBadRequest, HttpResponseServerError, \
    HttpResponseForbidden
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView

from blog.models import Post
from newsAPI import settings


CATEGORY_CHOICES = [
    'business',
    'entertainment',
    # 'education',
    'health',
    'sports',
    'technology',
    'science',
    'general',
]


class NewsListView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    # paginate_by = 10

    def get_queryset(self):
        # print(self.qwargs['cat_slug'])
        api_key = settings.NEWS_API_KEY # оголошено у .env
        url = f'https://newsapi.org/v2/top-headlines?country=us&apiKey={api_key}'
        resp = requests.get(url).json()

        return resp.get('articles', [])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'NewsAPI'
        context['category'] = CATEGORY_CHOICES
        return context

#
# def posts_by_category(request, cat_slug):
#     return HttpResponse(f'category: {cat_slug}')


class NewsCategory(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        api_key = settings.NEWS_API_KEY  # оголошено у .env
        cat = self.kwargs['cat_slug']
        url = f'https://newsapi.org/v2/top-headlines?country=us&category={cat}&apiKey={api_key}'
        resp = requests.get(url).json()

        return resp.get('articles', [])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = self.kwargs['cat_slug']
        context['title'] = 'NewsAPI' + ' - "' + cat.title() + '"' if cat != 'general' else 'NewAPI'
        context['posts_cat'] = f'category "{cat.title()}"' if cat != 'general' else ''
        context['cat_slug'] = cat.title() if cat != 'general' else ''
        context['category'] = CATEGORY_CHOICES
        return context

class AddPostView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'



def archive(request, year):
    if int(year) > 2025:
        # raise Http404() # відображення сторінки з кодом 404 (функція page_not_found(request, exception))
        # return redirect('posts') # редірект з кодом 302 - url змінився тимчасово
        return redirect('home', permanent=True) # редірект з кодом 301 - постійний url permanent=True

    return HttpResponse(f'<h1>Архів за {year} рік</h1>')



def page_not_found(request, exception):
    """ Відображення сторінки 404 """
    return HttpResponseNotFound(f'<h1>Page not found</h1><p>Error: 404</p>')
    # return HttpResponseBadRequest(f'<h1>Bad Request</h1>', status=400)
    # return HttpResponseServerError(str(exception))
    # return HttpResponseForbidden(f'<h1>Доступ заборонений</h1><p>{exception}</p>')

newsAPI/user/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

from user.forms import LoginUserForm, RegisterUserForm


# class LoginView:
#     pass
#
#
# class LogoutView:
#     pass
def login_user(request):
    if request.method == "POST":
        form = LoginUserForm(request.POST)
        if form.is_valid():
            data_form = form.cleaned_data
            user = authenticate(username=data_form['username'], password=data_form['password'])
            if user and user.is_active:
                login(request, user)
                return redirect('home')

        error = 'Невірний логін або пароль'
        return render(request, "user/login.html", {"form": form, 'error': error})

    else:
        form = LoginUserForm()
        return render(request, "user/login.html", {"form": form})




def logout_user(request):
    logout(request)
    return redirect('home')


def register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'user/login.html', {"form": form, 'user_data': user})

        return render(request, "user/register.html", {"error": form.errors, "form": form})

    else:
        from faker import Faker
        fake = Faker()

        form = RegisterUserForm()
        new_user = {
            'username': fake.user_name(),
            'email': fake.email(),
            'password': '1111',
            'first_name': fake.first_name(),
            'last_name': fake.last_name(),
        }

        return render(request, 'user/register.html', context={'form': form, 'new_user': new_user})


def user_by_id(request):
    return None


def list_users(request):
    return None

newsAPI/blog/templates/blog/base_blog.html
{% extends 'base.html' %}

newsAPI/blog/templates/blog/index.html
{% extends 'blog/base_blog.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1 class="mb-5">Posts: {{ posts_cat }}</h1>
    {% for post in posts %}
    <div class="card mb-3">
        <h6 class="card-subtitle mb-2 text-body-secondary">Source: {{ post.source.name }}</h6>
        <img src="{{ post.urlToImage }}" class="card-img-top" alt="{{ post.title }}">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
<!--            <p class="card-text">{{ post.content }}</p>-->
            <p class="card-text">{{ post.description|truncatewords:200 }}</p>
            <p class="card-link"><small class="text-body-secondary">Author: {{ post.author }}</small></p>
            <p class="card-link"><small class="text-body-secondary">Data published: {{ post.publishedAt }}</small></p>
            <a href="{{ post.url }}" class="btn btn-primary">Read all</a>
        </div>
    </div>

    {% endfor %}
{% endblock content %}

newsAPI/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
          crossorigin="anonymous">
    <title>
        {% block title %}
            Block Engine
        {% endblock title %}
    </title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">BlogMaster</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#">Add post</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories {% if cat_slug %} -> {{ cat_slug }} {% endif %}
          </a>
          <ul class="dropdown-menu">
            {% for cat in category %}
            <li><a class="dropdown-item" href="{% url 'posts_by_category' cat %}">{{ cat|title }}</a></li>
        {% comment %}
            <li><hr class="dropdown-divider"></li>
        {% endcomment %}
            {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#"> {{ user.username }} </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:logout' %}"> Exit</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:login' %}">Увійти/Реєстрація</a>
        </li>
        {% endif %}

      </ul>
  </div>
</nav>

<div class="container">
    <div class="row">
<!--        <div class="col-6">-->
        <div class="col-6 offset-md-2">
            {% block content %}
                There is no any  content
            {% endblock content %}
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous">
    </script>
</body>
</html>

newsAPI/user/templates/user/login.html
{% extends 'blog/base_blog.html' %}

{% block title %}
    Login user
{% endblock %}

{% block content %}
    <h1 class="m-5">Log in:</h1>
    <p style="color: red">{{ error }}</p>
    <form action="{% url 'user:login' %}" method="post">
    {% csrf_token %}
      <div class="mb-3">
        <label for="login" class="form-label">Email address</label>
        <input type="text" class="form-control" id="login" aria-describedby="loginHelp" name="username"
               {% if user %} value="{{ user_data.username }}" {% endif %}>
        <div id="loginHelp" class="form-text">Enter your email to login.</div>
      </div>
      <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
      </div>
      <div class="mb-3 form-check">
        <a href="{% url 'user:sign_up' %}">Реєстрація</a>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock content %}

newsAPI/user/templates/user/register.html
{% extends 'blog/base_blog.html' %}

{% block title %}
    Login user
{% endblock %}

{% block content %}
    <h1 class="m-5">Реєстрація:</h1>
    <p style="color: red">{{ error }}</p>
    <form action="{% url 'user:sign_up' %}" method="post">
    {% csrf_token %}
      <div class="form-floating mb-3">
        <input type="text" class="form-control" id="login" placeholder="login" value="{{ new_user.username }}" name="username">
        <label for="login" class="form-label">Login</label>
<!--        <div id="loginHelp" class="form-text">Enter your email to login.</div>-->
      </div>
      <div class="form-floating mb-3">
        <input type="firstname" class="form-control" id="firstnameInput" placeholder="firstname" value="{{ new_user.first_name }}" name="first_name">
        <label for="firstnameInput">Ім'я</label>
      </div>
      <div class="form-floating mb-3">
        <input type="lastname" class="form-control" id="lastnameInput" placeholder="lastname" value="{{ new_user.last_name }}" name="last_name">
        <label for="lastnameInput">Прізвище</label>
      </div>
      <div class="form-floating mb-3">
        <input type="email" class="form-control" id="floatingEmail" placeholder="Email" value="{{ new_user.email }}" name="email">
        <label for="floatingEmail">Email</label>
      </div>
      <div class="form-floating mb-3">
        <input type="password" class="form-control" id="password" placeholder="password" value="{{ new_user.password }}" name="password">
        <label for="password" class="form-label">Пароль</label>
      </div>
      <div class="form-floating mb-3">
        <input type="password" class="form-control" id="password2" placeholder="password2" value="{{ new_user.password }}" name="password2">
        <label for="password2" class="form-label">Повтор пароля</label>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock content %}